### ISSUE TITLE
Deduplicator/expert.py error

### ISSUE THREAD

**Issue by Roslekas** [certtools/intelmq#966]
Hi,

after adding node(collector and parser) getting error in deduplicator. What it could be ?

![image](https://cloud.githubusercontent.com/assets/16913780/25803741/01047e22-3401-11e7-86e3-6451b57fbfdd.png)

Thanks

**Comment by wagner-certat** [comment]
What version of intelmq do you use?

ignore_keys has been renamed to filter_keys, see also https://github.com/certtools/intelmq/blob/master/NEWS.md#configuration-1

**Comment by Roslekas** [comment]
Using 1.0.0.dev6, i'll try to upgrade version to 1.0.0.dev7

**Comment by Roslekas** [comment]
How to upgrade version to dev7 ? i followed by the Upgrade instructions: https://github.com/certtools/intelmq/blob/master/docs/UPGRADING.md

![image](https://cloud.githubusercontent.com/assets/16913780/25840039/caf17ca2-34a2-11e7-89ec-76616146ec2d.png)

Thanks

**Comment by wagner-certat** [comment]
Can you please show your runtime configuration of your deduplicator?

**Comment by Roslekas** [comment]
"deduplicator-expert": {
        "parameters": {
            "filter_keys": "raw,time.observation",
            "filter_type": "blacklist",
            "redis_cache_db": 6,
            "redis_cache_host": "127.0.0.1",
            "redis_cache_password": null,
            "redis_cache_port": 6379,
            "redis_cache_ttl": 86400
        },
        "group": "Expert",
        "name": "Deduplicator",
        "module": "intelmq.bots.experts.deduplicator.expert",
        "description": "Deduplicator is the bot responsible for detection and removal of duplicate messages. Messages get cached for <redis_cache_ttl> seconds. If found in the cache, it is assumed to be a duplicate."
    },

**Comment by wagner-certat** [comment]
That config is for dev7, but you have dev6.

Rename `filter_keys` to `ignore_keys`. `filter_type` will be ignored in this version.

But where do you have this config from? In the BOTS file from dev6 on pypi the correct keys are used.

**Comment by Roslekas** [comment]
Running on Ubuntu 16.04, and followed by blow listed installation instructions, maybe it is all instructions ? how to get dev7 ?

apt-get install python3 python3-pip
apt-get install git build-essential libffi-dev
apt-get install python3-dev
apt-get install redis-server

pip install intelmq
 git clone https://github.com/certtools/intelmq.git /tmp/intelmq
cd /tmp/intelmq
sudo -s
pip3 install -r REQUIREMENTS
pip3 install .
useradd -d /opt/intelmq -U -s /bin/bash intelmq
chmod -R 0770 /opt/intelmq

**Comment by Roslekas** [comment]
Changed as You suggested to "ignore_keys", deduplicator now works without errors but  got another error in gethostbyname/expert.py "Name or service not known"...

![image](https://cloud.githubusercontent.com/assets/16913780/25849065/9e4558ea-34c5-11e7-8300-59703495ed96.png)

**Comment by wagner-certat** [comment]
Thanks for the hint about the unclear install instructions. I now have split them analogous to the instructions in UPGRADING. Could you have a look if they are (more) clear now, please?

dev7 hasn't been release yet.

Concerning the error in gethostbyname: This has been fixed in master in january. I will release a dev7 today, the latest release is already quite old.

**Comment by wagner-certat** [comment]
I released dev7, please update and check again. The error should be gone. (And checkout https://github.com/certtools/intelmq/blob/master/NEWS.md ie. you now have to upgrade the deduplicator config again - sorry, but you now have an up2date version :) )

**Comment by Roslekas** [comment]
Thanks, upgraded to dev7, dedublicator and gethostbyname works, but still have problem with MISP parser, but it is another issue...:/

![image](https://cloud.githubusercontent.com/assets/16913780/25887535/3de0d4a6-356b-11e7-873c-916a8e7f6097.png)

**Comment by wagner-certat** [comment]
Duplicate of your own #965
